version: '3.5'

services:
  nginx:
    image: nginx
    container_name: carecoonect-nginx
    restart: always
    ports:
      - "9393:80"
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: careconnect-php
    restart: always
    volumes:
      - ../:/var/www/html